const Transaction = require('../models/Transaction');
const Order = require('../models/Order');
const Document = require('../models/Document');
const Software = require('../models/Software');
const pathManager = require('../config/pathManager');
const mpesaService = require('../services/mpesaService');
const crypto = require('crypto');

// Initiate STK Push (autogenerated payment)
exports.initiateSTKPush = async (req, res) => {
  try {
    const { phoneNumber, itemId, itemType } = req.body;
    const userId = req.user.id;

    // Validate phone number
    const phoneRegex = /^(?:\+254|0)[17]\d{8}$/;
    if (!phoneNumber || !phoneRegex.test(phoneNumber)) {
      return res.status(400).json({ 
        message: 'Valid Kenyan phone number required (e.g., 0712345678)' 
      });
    }

    // Get item details
    const Model = itemType === 'document' ? Document : Software;
    const item = await Model.findById(itemId);
    if (!item) {
      return res.status(404).json({ message: 'Item not found' });
    }

    // Check if user already owns this item
    const existingOrder = await Order.findOne({
      user: userId,
      'items.itemId': itemId,
      status: 'completed'
    });
    if (existingOrder) {
      return res.status(400).json({ message: 'You already own this item' });
    }

    // Check for duplicate pending transaction
    const existingPending = await Transaction.findOne({
      user: userId,
      itemId,
      status: { $in: ['pending', 'processing'] },
      paymentMethod: 'autogenerated'
    });
    if (existingPending) {
      return res.status(400).json({ 
        message: 'You already have a pending payment. Please wait or check status.',
        transactionId: existingPending._id
      });
    }

    // Create pending transaction
    const transaction = await Transaction.create({
      user: userId,
      itemId: item._id,
      itemType,
      itemTitle: item.title,
      amount: item.price,
      paymentMethod: 'autogenerated',
      status: 'pending',
      phoneNumber,
      metadata: { 
        initiatedAt: new Date().toISOString(),
        itemTitle: item.title,
        itemPrice: item.price,
        ipAddress: req.ip,
        userAgent: req.headers['user-agent']
      }
    });

    // Initiate STK Push with M-Pesa
    const accountRef = `${itemType === 'document' ? 'DOC' : 'SW'}-${item._id.toString().slice(-6)}`;
    const mpesaResponse = await mpesaService.initiateSTKPush(
      phoneNumber,
      item.price,
      accountRef,
      `Payment for ${item.title}`
    );

    // Update transaction with M-Pesa details
    transaction.metadata.mpesaResponse = mpesaResponse;
    transaction.metadata.checkoutRequestId = mpesaResponse.CheckoutRequestID;
    transaction.status = 'processing';
    await transaction.save();

    console.log(`✅ STK Push initiated for transaction: ${transaction._id}`);

    res.json({
      success: true,
      message: 'STK Push initiated. Check your phone to complete payment.',
      transactionId: transaction._id,
      checkoutRequestId: mpesaResponse.CheckoutRequestID,
      status: 'processing'
    });
  } catch (error) {
    console.error('STK Push error:', error);
    res.status(500).json({ 
      success: false,
      message: 'Failed to initiate payment. Please try again or use manual payment.',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

// Initiate manual payment (screenshot upload)
exports.initiateManualPayment = async (req, res) => {
  try {
    const { itemId, itemType } = req.body;
    const userId = req.user.id;

    const Model = itemType === 'document' ? Document : Software;
    const item = await Model.findById(itemId);
    if (!item) {
      return res.status(404).json({ message: 'Item not found' });
    }

    // Check if user already owns this item
    const existingOrder = await Order.findOne({
      user: userId,
      'items.itemId': itemId,
      status: 'completed'
    });
    if (existingOrder) {
      return res.status(400).json({ message: 'You already own this item' });
    }

    // Check for existing pending transaction
    const existingPending = await Transaction.findOne({
      user: userId,
      itemId,
      status: 'pending',
      paymentMethod: 'manual'
    });
    if (existingPending) {
      return res.json({
        success: true,
        message: 'You already have a pending payment for this item',
        transactionId: existingPending._id,
        existing: true
      });
    }

    // Create new transaction
    const transaction = await Transaction.create({
      user: userId,
      itemId: item._id,
      itemType,
      itemTitle: item.title,
      amount: item.price,
      paymentMethod: 'manual',
      status: 'pending',
      metadata: { 
        initiatedAt: new Date().toISOString(),
        ipAddress: req.ip,
        userAgent: req.headers['user-agent']
      }
    });

    console.log(`✅ Manual payment initiated: ${transaction._id}`);

    res.status(201).json({
      success: true,
      message: 'Manual payment initiated. Please send money and upload screenshot.',
      transactionId: transaction._id,
      amount: item.price,
      businessNumber: process.env.BUSINESS_PHONE || '0768784909',
      businessName: process.env.BUSINESS_NAME || 'DocuSoft Store'
    });
  } catch (error) {
    console.error('Manual payment initiation error:', error);
    res.status(500).json({ 
      success: false,
      message: 'Failed to initiate manual payment' 
    });
  }
};

// Upload screenshot for manual payment
exports.uploadScreenshot = async (req, res) => {
  try {
    const { transactionId } = req.params;
    const userId = req.user.id;

    const transaction = await Transaction.findById(transactionId);
    if (!transaction) {
      return res.status(404).json({ message: 'Transaction not found' });
    }

    if (transaction.user.toString() !== userId) {
      return res.status(403).json({ message: 'Not authorized' });
    }

    if (transaction.status !== 'pending') {
      return res.status(400).json({ 
        message: `This payment is already ${transaction.status}` 
      });
    }

    if (!req.file) {
      return res.status(400).json({ message: 'No screenshot uploaded' });
    }

    // Validate file type
    const allowedTypes = ['image/jpeg', 'image/png', 'image/jpg', 'image/webp'];
    if (!allowedTypes.includes(req.file.mimetype)) {
      return res.status(400).json({ 
        message: 'Invalid file type. Please upload JPG, PNG, or WEBP image.' 
      });
    }

    // Validate file size (max 5MB)
    if (req.file.size > 5 * 1024 * 1024) {
      return res.status(400).json({ 
        message: 'File too large. Max size 5MB.' 
      });
    }

    // Store screenshot with relative path
    const relativePath = `screenshots/${req.file.filename}`;
    transaction.screenshotUrl = pathManager.getPublicUrl(relativePath);
    transaction.screenshotPath = req.file.path;
    transaction.metadata.uploadedAt = new Date().toISOString();
    transaction.metadata.uploadedFile = req.file.originalname;
    transaction.metadata.uploadedFileSize = req.file.size;
    await transaction.save();

    console.log(`✅ Screenshot uploaded for transaction: ${transactionId}`);

    // Send email notification to admin (if email service configured)
    // await sendAdminNotification(transaction);

    res.json({
      success: true,
      message: 'Screenshot uploaded successfully. Awaiting admin verification.',
      transactionId: transaction._id,
      status: transaction.status
    });
  } catch (error) {
    console.error('Screenshot upload error:', error);
    res.status(500).json({ message: 'Failed to upload screenshot' });
  }
};

// Check payment status for an item (with caching)
let statusCache = new Map();

exports.checkPaymentStatus = async (req, res) => {
  try {
    const { itemId } = req.params;
    const userId = req.user.id;

    // Check cache first (5 second TTL)
    const cacheKey = `${userId}-${itemId}`;
    const cached = statusCache.get(cacheKey);
    if (cached && Date.now() - cached.timestamp < 5000) {
      return res.json(cached.data);
    }

    // Check if order exists (completed purchase)
    const order = await Order.findOne({
      user: userId,
      'items.itemId': itemId,
      status: 'completed'
    });

    if (order) {
      const response = {
        purchased: true,
        status: 'completed',
        orderId: order._id,
        message: 'You own this item',
        downloadCount: order.items.find(i => i.itemId.toString() === itemId)?.downloadCount || 0
      };
      statusCache.set(cacheKey, { data: response, timestamp: Date.now() });
      return res.json(response);
    }

    // Check for any transaction
    const transaction = await Transaction.findOne({
      user: userId,
      itemId
    }).sort({ createdAt: -1 });

    if (transaction) {
      let statusMessage = '';
      switch (transaction.status) {
        case 'pending':
          statusMessage = 'Payment pending verification. Please wait.';
          break;
        case 'processing':
          statusMessage = 'Payment processing. Check your phone for M-Pesa prompt.';
          break;
        case 'approved':
          statusMessage = 'Payment approved, order being processed.';
          break;
        case 'completed':
          statusMessage = 'Payment completed. You can download now.';
          break;
        case 'rejected':
          statusMessage = `Payment rejected: ${transaction.rejectionReason || 'Please contact support.'}`;
          break;
        case 'failed':
          statusMessage = 'Payment failed. Please try again.';
          break;
        default:
          statusMessage = 'Payment status unknown. Contact support.';
      }

      const response = {
        purchased: false,
        transactionId: transaction._id,
        status: transaction.status,
        message: statusMessage,
        createdAt: transaction.createdAt
      };
      statusCache.set(cacheKey, { data: response, timestamp: Date.now() });
      return res.json(response);
    }

    const response = {
      purchased: false,
      status: 'not_paid',
      message: 'No payment found for this item'
    };
    statusCache.set(cacheKey, { data: response, timestamp: Date.now() });
    res.json(response);
  } catch (error) {
    console.error('Check payment status error:', error);
    res.status(500).json({ message: 'Failed to check status' });
  }
};

// Get user's pending transactions
exports.getUserPendingTransactions = async (req, res) => {
  try {
    const userId = req.user.id;
    const pending = await Transaction.find({
      user: userId,
      status: { $in: ['pending', 'processing'] },
      paymentMethod: 'manual',
      screenshotUrl: { $exists: true, $ne: null }
    }).sort({ createdAt: -1 });

    console.log(`📊 Found ${pending.length} pending transactions for user ${userId}`);
    res.json(pending);
  } catch (error) {
    console.error('Get user pending transactions error:', error);
    res.status(500).json({ message: 'Failed to fetch pending transactions' });
  }
};

// M-Pesa callback (webhook) - Production ready
exports.mpesaCallback = async (req, res) => {
  try {
    const data = req.body;
    console.log('📱 M-Pesa callback received:', JSON.stringify(data, null, 2));

    const { CheckoutRequestID, ResultCode, ResultDesc } = data.Body?.stkCallback || {};

    if (!CheckoutRequestID) {
      console.log('❌ No CheckoutRequestID in callback');
      return res.status(200).json({ ResultCode: 1, ResultDesc: 'Invalid callback data' });
    }

    // Find the transaction
    const transaction = await Transaction.findOne({
      'metadata.checkoutRequestId': CheckoutRequestID
    });

    if (!transaction) {
      console.log('❌ Transaction not found for CheckoutRequestID:', CheckoutRequestID);
      return res.status(200).json({ ResultCode: 1, ResultDesc: 'Transaction not found' });
    }

    // Prevent double processing
    if (transaction.status === 'completed') {
      console.log('⚠️ Transaction already completed:', transaction._id);
      return res.status(200).json({ ResultCode: 0, ResultDesc: 'Already processed' });
    }

    if (ResultCode === 0) {
      // Payment successful
      console.log(`✅ Payment successful for transaction: ${transaction._id}`);
      
      transaction.status = 'completed';
      transaction.metadata.callbackData = data;
      transaction.metadata.mpesaCode = data.Body?.stkCallback?.MerchantRequestID;
      transaction.metadata.completedAt = new Date().toISOString();
      transaction.metadata.callbackReceivedAt = new Date().toISOString();
      await transaction.save();

      // Create order immediately
      const Model = transaction.itemType === 'document' ? Document : Software;
      const item = await Model.findById(transaction.itemId);
      
      if (item) {
        const order = await Order.create({
          user: transaction.user,
          items: [{
            itemId: transaction.itemId,
            itemType: transaction.itemType,
            title: item.title,
            price: transaction.amount,
            downloadCount: 0
          }],
          totalAmount: transaction.amount,
          paymentMethod: transaction.paymentMethod,
          transactionId: transaction._id,
          status: 'completed',
          completedAt: new Date()
        });
        
        transaction.orderCreated = true;
        transaction.orderId = order._id;
        await transaction.save();
        
        console.log(`✅ Order created: ${order._id}`);
        
        // TODO: Send email confirmation to user
        // await sendPaymentConfirmationEmail(transaction.user, item, order);
      }
    } else {
      // Payment failed
      console.log(`❌ Payment failed for transaction ${transaction._id}: ${ResultDesc}`);
      
      transaction.status = 'failed';
      transaction.metadata.callbackData = data;
      transaction.metadata.failureReason = ResultDesc;
      transaction.metadata.failedAt = new Date().toISOString();
      await transaction.save();
    }

    // Always respond with success to M-Pesa
    res.status(200).json({ ResultCode: 0, ResultDesc: 'Success' });
  } catch (error) {
    console.error('M-Pesa callback error:', error);
    res.status(200).json({ ResultCode: 1, ResultDesc: 'Error processing callback' });
  }
};

// Get transaction details (admin)
exports.getTransactionDetails = async (req, res) => {
  try {
    const { id } = req.params;
    const transaction = await Transaction.findById(id)
      .populate('user', 'name email phone')
      .populate('approvedBy', 'name email');

    if (!transaction) {
      return res.status(404).json({ message: 'Transaction not found' });
    }

    res.json(transaction);
  } catch (error) {
    console.error('Get transaction details error:', error);
    res.status(500).json({ message: 'Failed to fetch transaction details' });
  }
};

// Helper to create order from transaction (used by admin approval)
async function createOrderFromTransaction(transactionId) {
  try {
    const transaction = await Transaction.findById(transactionId);
    if (!transaction || transaction.orderCreated) return;

    const Model = transaction.itemType === 'document' ? Document : Software;
    const item = await Model.findById(transaction.itemId);
    if (!item) return;

    const order = await Order.create({
      user: transaction.user,
      items: [{
        itemId: transaction.itemId,
        itemType: transaction.itemType,
        title: item.title,
        price: transaction.amount,
        downloadCount: 0
      }],
      totalAmount: transaction.amount,
      paymentMethod: transaction.paymentMethod,
      transactionId: transaction._id,
      status: 'completed',
      completedAt: new Date()
    });

    transaction.status = 'completed';
    transaction.orderCreated = true;
    transaction.orderId = order._id;
    await transaction.save();

    console.log(`✅ Order created for transaction ${transactionId}`);
    return order;
  } catch (error) {
    console.error('Failed to create order from transaction:', error);
    throw error;
  }
}

exports.createOrderFromTransaction = createOrderFromTransaction;