const Transaction = require('../models/Transaction');
const Order = require('../models/Order');
const Document = require('../models/Document');
const Software = require('../models/Software');
const pathManager = require('../config/pathManager');
const mpesaService = require('../services/mpesaService');

// ============ STK Push (Auto‑generated payment) ============
exports.initiateSTKPush = async (req, res) => {
  try {
    const { phoneNumber, itemId, itemType } = req.body;
    const userId = req.user.id;

    const phoneRegex = /^(?:\+254|0)[17]\d{8}$/;
    if (!phoneNumber || !phoneRegex.test(phoneNumber)) {
      return res.status(400).json({ message: 'Valid Kenyan phone number required (e.g., 0712345678)' });
    }

    const Model = itemType === 'document' ? Document : Software;
    const item = await Model.findById(itemId);
    if (!item) return res.status(404).json({ message: 'Item not found' });

    const existingOrder = await Order.findOne({ user: userId, 'items.itemId': itemId, status: 'completed' });
    if (existingOrder) return res.status(400).json({ message: 'You already own this item' });

    const existingPending = await Transaction.findOne({
      user: userId,
      itemId,
      status: { $in: ['pending', 'processing'] },
      paymentMethod: 'autogenerated'
    });
    if (existingPending) {
      return res.status(400).json({
        message: 'You already have a pending payment. Please wait or check status.',
        transactionId: existingPending._id
      });
    }

    const transaction = await Transaction.create({
      user: userId,
      itemId: item._id,
      itemType,
      itemTitle: item.title,
      amount: item.price,
      paymentMethod: 'autogenerated',
      status: 'pending',
      phoneNumber,
      metadata: {
        initiatedAt: new Date().toISOString(),
        itemTitle: item.title,
        itemPrice: item.price,
        ipAddress: req.ip,
        userAgent: req.headers['user-agent']
      }
    });

    const accountRef = `${itemType === 'document' ? 'DOC' : 'SW'}-${item._id.toString().slice(-6)}`;
    const mpesaResponse = await mpesaService.initiateSTKPush(
      phoneNumber,
      item.price,
      accountRef,
      `Payment for ${item.title}`
    );

    transaction.metadata.mpesaResponse = mpesaResponse;
    transaction.metadata.checkoutRequestId = mpesaResponse.CheckoutRequestID;
    transaction.status = 'processing';
    await transaction.save();

    console.log(`✅ STK Push initiated for transaction: ${transaction._id}`);
    res.json({
      success: true,
      message: 'STK Push initiated. Check your phone to complete payment.',
      transactionId: transaction._id,
      checkoutRequestId: mpesaResponse.CheckoutRequestID,
      status: 'processing'
    });
  } catch (error) {
    console.error('STK Push error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to initiate payment. Please try again or use manual payment.'
    });
  }
};

// ============ Manual payment initiation ============
exports.initiateManualPayment = async (req, res) => {
  try {
    const { itemId, itemType } = req.body;
    const userId = req.user.id;

    const Model = itemType === 'document' ? Document : Software;
    const item = await Model.findById(itemId);
    if (!item) return res.status(404).json({ message: 'Item not found' });

    const existingOrder = await Order.findOne({ user: userId, 'items.itemId': itemId, status: 'completed' });
    if (existingOrder) return res.status(400).json({ message: 'You already own this item' });

    const existingPending = await Transaction.findOne({
      user: userId,
      itemId,
      status: 'pending',
      paymentMethod: 'manual'
    });
    if (existingPending) {
      return res.json({
        success: true,
        message: 'You already have a pending payment for this item',
        transactionId: existingPending._id,
        existing: true
      });
    }

    const transaction = await Transaction.create({
      user: userId,
      itemId: item._id,
      itemType,
      itemTitle: item.title,
      amount: item.price,
      paymentMethod: 'manual',
      status: 'pending',
      metadata: {
        initiatedAt: new Date().toISOString(),
        ipAddress: req.ip,
        userAgent: req.headers['user-agent']
      }
    });

    console.log(`✅ Manual payment initiated: ${transaction._id}`);
    res.status(201).json({
      success: true,
      message: 'Manual payment initiated. Please send money and upload screenshot or paste confirmation.',
      transactionId: transaction._id,
      amount: item.price,
      businessNumber: process.env.BUSINESS_PHONE || '0768784909',
      businessName: process.env.BUSINESS_NAME || 'DocuSoft Store'
    });
  } catch (error) {
    console.error('Manual payment initiation error:', error);
    res.status(500).json({ success: false, message: 'Failed to initiate manual payment' });
  }
};

// ============ Upload screenshot (local file) ============
exports.uploadScreenshot = async (req, res) => {
  try {
    const { transactionId } = req.params;
    const userId = req.user.id;

    if (!req.file) {
      return res.status(400).json({ message: 'No screenshot uploaded' });
    }

    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp'];
    if (!allowedTypes.includes(req.file.mimetype)) {
      return res.status(400).json({ message: 'Invalid file type. Please upload JPG, PNG, GIF, or WEBP image.' });
    }

    if (req.file.size > 10 * 1024 * 1024) {
      return res.status(413).json({ message: 'Screenshot too large. Max 10MB.' });
    }

    const transaction = await Transaction.findById(transactionId);
    if (!transaction) return res.status(404).json({ message: 'Transaction not found' });
    if (transaction.user.toString() !== userId) return res.status(403).json({ message: 'Not authorized' });
    if (transaction.status !== 'pending') return res.status(400).json({ message: `Payment already ${transaction.status}` });

    const relativePath = `screenshots/${req.file.filename}`;
    transaction.screenshotUrl = pathManager.getPublicUrl(relativePath);
    transaction.screenshotPath = req.file.path;
    
    if (!transaction.metadata) transaction.metadata = {};
    transaction.metadata.uploadedAt = new Date().toISOString();
    transaction.metadata.uploadType = 'screenshot';
    
    await transaction.save();

    console.log(`✅ Screenshot saved for transaction: ${transactionId}`);
    console.log(`   Screenshot URL: ${transaction.screenshotUrl}`);
    
    res.json({
      success: true,
      message: 'Screenshot uploaded. Awaiting admin verification.',
      transactionId: transaction._id
    });
  } catch (error) {
    console.error('Screenshot upload error:', error);
    res.status(500).json({ message: 'Failed to upload screenshot' });
  }
};

// ============ Submit payment confirmation message (text) ============
exports.submitConfirmationMessage = async (req, res) => {
  try {
    const { transactionId } = req.params;
    const { message } = req.body;
    const userId = req.user.id;

    if (!message || !message.trim()) {
      return res.status(400).json({ message: 'Confirmation message is required' });
    }

    const transaction = await Transaction.findById(transactionId);
    if (!transaction) return res.status(404).json({ message: 'Transaction not found' });
    if (transaction.user.toString() !== userId) return res.status(403).json({ message: 'Not authorized' });
    if (transaction.status !== 'pending') return res.status(400).json({ message: `Payment already ${transaction.status}` });

    if (!transaction.metadata) transaction.metadata = {};
    transaction.metadata.paymentConfirmation = message.trim();
    transaction.metadata.uploadedAt = new Date().toISOString();
    transaction.metadata.uploadType = 'message';
    
    await transaction.save();

    console.log(`✅ Payment confirmation message saved for transaction: ${transactionId}`);
    console.log(`   Message: ${message.substring(0, 100)}...`);
    
    res.json({
      success: true,
      message: 'Payment confirmation received. Awaiting admin verification.',
      transactionId: transaction._id
    });
  } catch (error) {
    console.error('Confirmation error:', error);
    res.status(500).json({ message: 'Failed to save confirmation' });
  }
};

// ============ Check payment status ============
let statusCache = new Map();

exports.checkPaymentStatus = async (req, res) => {
  try {
    const { itemId } = req.params;
    const userId = req.user.id;

    const cacheKey = `${userId}-${itemId}`;
    const cached = statusCache.get(cacheKey);
    if (cached && Date.now() - cached.timestamp < 5000) {
      return res.json(cached.data);
    }

    const order = await Order.findOne({ user: userId, 'items.itemId': itemId, status: 'completed' });
    if (order) {
      const response = {
        purchased: true,
        status: 'completed',
        orderId: order._id,
        message: 'You own this item'
      };
      statusCache.set(cacheKey, { data: response, timestamp: Date.now() });
      return res.json(response);
    }

    const transaction = await Transaction.findOne({ user: userId, itemId }).sort({ createdAt: -1 });
    if (transaction) {
      let statusMessage = '';
      switch (transaction.status) {
        case 'pending': statusMessage = 'Payment pending verification. Please wait.'; break;
        case 'processing': statusMessage = 'Payment processing. Check your phone for M-Pesa prompt.'; break;
        case 'approved': statusMessage = 'Payment approved, order being processed.'; break;
        case 'completed': statusMessage = 'Payment completed. You can download now.'; break;
        case 'rejected': statusMessage = `Payment rejected: ${transaction.rejectionReason || 'Please contact support.'}`; break;
        case 'failed': statusMessage = 'Payment failed. Please try again.'; break;
        default: statusMessage = 'Payment status unknown. Contact support.';
      }
      const response = {
        purchased: false,
        transactionId: transaction._id,
        status: transaction.status,
        message: statusMessage,
        createdAt: transaction.createdAt
      };
      statusCache.set(cacheKey, { data: response, timestamp: Date.now() });
      return res.json(response);
    }

    const response = { purchased: false, status: 'not_paid', message: 'No payment found for this item' };
    statusCache.set(cacheKey, { data: response, timestamp: Date.now() });
    res.json(response);
  } catch (error) {
    console.error('Check payment status error:', error);
    res.status(500).json({ message: 'Failed to check status' });
  }
};

// ============ Get user's pending transactions ============
exports.getUserPendingTransactions = async (req, res) => {
  try {
    const userId = req.user.id;
    const pending = await Transaction.find({
      user: userId,
      status: 'pending',
      paymentMethod: 'manual'
    }).sort({ createdAt: -1 });

    console.log(`📊 Found ${pending.length} pending transactions for user ${userId}`);
    
    pending.forEach(t => {
      console.log(`   Transaction ${t._id}:`, {
        hasScreenshot: !!t.screenshotUrl,
        hasConfirmation: !!t.metadata?.paymentConfirmation,
        status: t.status
      });
    });
    
    res.json(pending);
  } catch (error) {
    console.error('Get user pending transactions error:', error);
    res.status(500).json({ message: 'Failed to fetch pending transactions' });
  }
};

// ============ M-Pesa callback ============
exports.mpesaCallback = async (req, res) => {
  try {
    const data = req.body;
    console.log('📱 M-Pesa callback received:', JSON.stringify(data, null, 2));

    const { CheckoutRequestID, ResultCode, ResultDesc } = data.Body?.stkCallback || {};
    if (!CheckoutRequestID) {
      return res.status(200).json({ ResultCode: 1, ResultDesc: 'Invalid callback data' });
    }

    const transaction = await Transaction.findOne({ 'metadata.checkoutRequestId': CheckoutRequestID });
    if (!transaction) {
      return res.status(200).json({ ResultCode: 1, ResultDesc: 'Transaction not found' });
    }

    if (transaction.status === 'completed') {
      return res.status(200).json({ ResultCode: 0, ResultDesc: 'Already processed' });
    }

    if (ResultCode === 0) {
      transaction.status = 'completed';
      transaction.metadata.callbackData = data;
      transaction.metadata.mpesaCode = data.Body?.stkCallback?.MerchantRequestID;
      transaction.metadata.completedAt = new Date().toISOString();
      await transaction.save();

      const Model = transaction.itemType === 'document' ? Document : Software;
      const item = await Model.findById(transaction.itemId);
      if (item) {
        const order = await Order.create({
          user: transaction.user,
          items: [{
            itemId: transaction.itemId,
            itemType: transaction.itemType,
            title: item.title,
            price: transaction.amount,
            downloadCount: 0
          }],
          totalAmount: transaction.amount,
          paymentMethod: transaction.paymentMethod,
          transactionId: transaction._id,
          status: 'completed',
          completedAt: new Date()
        });
        transaction.orderCreated = true;
        transaction.orderId = order._id;
        await transaction.save();
        console.log(`✅ Order created: ${order._id}`);
      }
    } else {
      transaction.status = 'failed';
      transaction.metadata.callbackData = data;
      transaction.metadata.failureReason = ResultDesc;
      await transaction.save();
    }

    res.status(200).json({ ResultCode: 0, ResultDesc: 'Success' });
  } catch (error) {
    console.error('M-Pesa callback error:', error);
    res.status(200).json({ ResultCode: 1, ResultDesc: 'Error processing callback' });
  }
};

// ============ Helper to create order from transaction (admin approval) ============
const createOrderFromTransaction = async (transactionId) => {
  const transaction = await Transaction.findById(transactionId);
  if (!transaction || transaction.orderCreated) return;
  const Model = transaction.itemType === 'document' ? Document : Software;
  const item = await Model.findById(transaction.itemId);
  if (!item) return;
  const order = await Order.create({
    user: transaction.user,
    items: [{
      itemId: transaction.itemId,
      itemType: transaction.itemType,
      title: item.title,
      price: transaction.amount,
      downloadCount: 0
    }],
    totalAmount: transaction.amount,
    paymentMethod: transaction.paymentMethod,
    transactionId: transaction._id,
    status: 'completed',
    completedAt: new Date()
  });
  transaction.status = 'completed';
  transaction.orderCreated = true;
  transaction.orderId = order._id;
  await transaction.save();
  return order;
};

exports.createOrderFromTransaction = createOrderFromTransaction;