const Transaction = require('../../models/docusoft/Transaction');
const Order = require('../../models/docusoft/Order');
const Document = require('../../models/docusoft/Document');
const Software = require('../../models/docusoft/Software');
const mpesaService = require('../../services/docusoft/mpesaService');

// ============ STK Push ============
exports.initiateSTKPush = async (req, res) => {
  try {
    const { phoneNumber, itemId, itemType } = req.body;
    const userId = req.user.id;

    if (!/^(?:\+254|0)[17]\d{8}$/.test(phoneNumber)) {
      return res.status(400).json({ message: 'Valid Kenyan phone number required' });
    }

    const Model = itemType === 'document' ? Document : Software;
    const item = await Model.findById(itemId);
    if (!item) return res.status(404).json({ message: 'Item not found' });

    const existingOrder = await Order.findOne({ user: userId, 'items.itemId': itemId, status: 'completed' });
    if (existingOrder) return res.status(400).json({ message: 'You already own this item' });

    const existingPending = await Transaction.findOne({
      user: userId, itemId,
      status: { $in: ['pending', 'processing'] },
      paymentMethod: 'autogenerated'
    });
    if (existingPending) {
      return res.status(400).json({ message: 'You already have a pending payment', transactionId: existingPending._id });
    }

    const transaction = await Transaction.create({
      user: userId, itemId: item._id, itemType,
      itemTitle: item.title, amount: item.price,
      paymentMethod: 'autogenerated', status: 'pending',
      phoneNumber,
      metadata: { initiatedAt: new Date().toISOString() }
    });

    const accountRef = `${itemType === 'document' ? 'DOC' : 'SW'}-${item._id.toString().slice(-6)}`;
    const mpesaResponse = await mpesaService.initiateSTKPush(phoneNumber, item.price, accountRef, `Payment for ${item.title}`);

    transaction.metadata.mpesaResponse = mpesaResponse;
    transaction.metadata.checkoutRequestId = mpesaResponse.CheckoutRequestID;
    transaction.status = 'processing';
    await transaction.save();

    res.json({
      success: true,
      message: 'STK Push initiated. Check your phone.',
      transactionId: transaction._id,
      checkoutRequestId: mpesaResponse.CheckoutRequestID
    });
  } catch (error) {
    console.error('STK Push error:', error);
    res.status(500).json({ success: false, message: 'Failed to initiate payment' });
  }
};

// ============ Manual Payment ============
exports.initiateManualPayment = async (req, res) => {
  try {
    const { itemId, itemType } = req.body;
    const userId = req.user.id;

    const Model = itemType === 'document' ? Document : Software;
    const item = await Model.findById(itemId);
    if (!item) return res.status(404).json({ message: 'Item not found' });

    const existingOrder = await Order.findOne({ user: userId, 'items.itemId': itemId, status: 'completed' });
    if (existingOrder) return res.status(400).json({ message: 'You already own this item' });

    const existingPending = await Transaction.findOne({ user: userId, itemId, status: 'pending', paymentMethod: 'manual' });
    if (existingPending) {
      return res.json({ success: true, message: 'You have a pending payment', transactionId: existingPending._id, existing: true });
    }

    const transaction = await Transaction.create({
      user: userId, itemId: item._id, itemType,
      itemTitle: item.title, amount: item.price,
      paymentMethod: 'manual', status: 'pending',
      metadata: { initiatedAt: new Date().toISOString() }
    });

    res.status(201).json({
      success: true,
      message: 'Manual payment initiated. Send money and upload screenshot.',
      transactionId: transaction._id,
      amount: item.price,
      businessNumber: process.env.BUSINESS_PHONE || '0768784909'
    });
  } catch (error) {
    console.error('Manual payment error:', error);
    res.status(500).json({ success: false, message: 'Failed to initiate payment' });
  }
};

// ============ Upload Screenshot ============
exports.uploadScreenshot = async (req, res) => {
  try {
    const { transactionId } = req.params;
    const userId = req.user.id;

    if (!req.file) {
      return res.status(400).json({ message: 'No screenshot uploaded' });
    }

    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp'];
    if (!allowedTypes.includes(req.file.mimetype)) {
      return res.status(400).json({ message: 'Invalid file type' });
    }

    if (req.file.size > 10 * 1024 * 1024) {
      return res.status(413).json({ message: 'Screenshot too large. Max 10MB.' });
    }

    const transaction = await Transaction.findById(transactionId);
    if (!transaction) return res.status(404).json({ message: 'Transaction not found' });
    if (transaction.user.toString() !== userId) return res.status(403).json({ message: 'Not authorized' });
    if (transaction.status !== 'pending') return res.status(400).json({ message: `Payment already ${transaction.status}` });

    const githubService = require('../../services/docusoft/githubService');
    const downloadUrl = await githubService.uploadFile(req.file.buffer, req.file.originalname);

    transaction.screenshotUrl = downloadUrl;
    if (!transaction.metadata) transaction.metadata = {};
    transaction.metadata.uploadedAt = new Date().toISOString();
    transaction.metadata.uploadType = 'screenshot';
    transaction.markModified('metadata');
    await transaction.save();

    res.json({ success: true, message: 'Screenshot uploaded. Awaiting verification.', transactionId: transaction._id });
  } catch (error) {
    console.error('Screenshot upload error:', error);
    res.status(500).json({ message: 'Failed to upload screenshot' });
  }
};

// ============ Submit Confirmation Message ============
exports.submitConfirmationMessage = async (req, res) => {
  try {
    const { transactionId } = req.params;
    const { message } = req.body;
    const userId = req.user.id;

    if (!message?.trim()) return res.status(400).json({ message: 'Confirmation message is required' });

    const transaction = await Transaction.findById(transactionId);
    if (!transaction) return res.status(404).json({ message: 'Transaction not found' });
    if (transaction.user.toString() !== userId) return res.status(403).json({ message: 'Not authorized' });
    if (transaction.status !== 'pending') return res.status(400).json({ message: `Payment already ${transaction.status}` });

    if (!transaction.metadata) transaction.metadata = {};
    transaction.metadata.paymentConfirmation = message.trim();
    transaction.metadata.uploadedAt = new Date().toISOString();
    transaction.metadata.uploadType = 'message';
    transaction.markModified('metadata');
    await transaction.save();

    res.json({ success: true, message: 'Confirmation received. Awaiting verification.', transactionId: transaction._id });
  } catch (error) {
    console.error('Confirmation error:', error);
    res.status(500).json({ message: 'Failed to save confirmation' });
  }
};

// ============ Check Payment Status ============
exports.checkPaymentStatus = async (req, res) => {
  try {
    const { itemId } = req.params;
    const userId = req.user.id;

    const order = await Order.findOne({ user: userId, 'items.itemId': itemId, status: 'completed' });
    if (order) return res.json({ purchased: true, status: 'completed', orderId: order._id });

    const transaction = await Transaction.findOne({ user: userId, itemId }).sort({ createdAt: -1 });
    if (transaction) {
      return res.json({
        purchased: false,
        transactionId: transaction._id,
        status: transaction.status,
        createdAt: transaction.createdAt
      });
    }

    res.json({ purchased: false, status: 'not_paid' });
  } catch (error) {
    console.error('Check status error:', error);
    res.status(500).json({ message: 'Failed to check status' });
  }
};

// ============ Get User Pending Transactions ============
exports.getUserPendingTransactions = async (req, res) => {
  try {
    const pending = await Transaction.find({ user: req.user.id, status: 'pending', paymentMethod: 'manual' }).sort({ createdAt: -1 });
    res.json(pending);
  } catch (error) {
    res.status(500).json({ message: 'Failed to fetch pending transactions' });
  }
};

// ============ M-Pesa Callback ============
exports.mpesaCallback = async (req, res) => {
  try {
    const { CheckoutRequestID, ResultCode } = req.body.Body?.stkCallback || {};
    if (!CheckoutRequestID) return res.status(200).json({ ResultCode: 1, ResultDesc: 'Invalid callback' });

    const transaction = await Transaction.findOne({ 'metadata.checkoutRequestId': CheckoutRequestID });
    if (!transaction || transaction.status === 'completed') return res.status(200).json({ ResultCode: 0, ResultDesc: 'Processed' });

    if (ResultCode === 0) {
      transaction.status = 'completed';
      transaction.metadata.completedAt = new Date().toISOString();
      await transaction.save();

      const Model = transaction.itemType === 'document' ? Document : Software;
      const item = await Model.findById(transaction.itemId);
      if (item) {
        await Order.create({
          user: transaction.user,
          items: [{ itemId: transaction.itemId, itemType: transaction.itemType, title: item.title, price: transaction.amount, downloadCount: 0 }],
          totalAmount: transaction.amount,
          paymentMethod: transaction.paymentMethod,
          transactionId: transaction._id,
          status: 'completed',
          completedAt: new Date()
        });
      }
    } else {
      transaction.status = 'failed';
      await transaction.save();
    }

    res.status(200).json({ ResultCode: 0, ResultDesc: 'Success' });
  } catch (error) {
    console.error('M-Pesa callback error:', error);
    res.status(200).json({ ResultCode: 1, ResultDesc: 'Error' });
  }
};

// ============ Debug ============
exports.debugTransaction = async (req, res) => {
  try {
    const transaction = await Transaction.findById(req.params.id);
    if (!transaction) return res.status(404).json({ message: 'Transaction not found' });
    res.json(transaction);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};