const mongoose = require('mongoose');

const orderItemSchema = new mongoose.Schema({
  itemId: { type: mongoose.Schema.Types.ObjectId, required: true, refPath: 'items.itemType' },
  itemType: { type: String, enum: ['document', 'software'], required: true },
  title: { type: String, required: true },
  price: { type: Number, required: true },
  downloadCount: { type: Number, default: 0 },
  lastDownloaded: Date
});

const orderSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  items: [orderItemSchema],
  totalAmount: { type: Number, required: true, min: 0 },
  status: { type: String, enum: ['pending', 'completed', 'failed', 'refunded'], default: 'pending' },
  paymentMethod: { type: String, enum: ['autogenerated', 'manual'], required: true },
  transactionId: { type: mongoose.Schema.Types.ObjectId, ref: 'Transaction', unique: true, sparse: true },
  completedAt: Date
}, { timestamps: true });

// Helper method to check if user can download an item
orderSchema.methods.canDownload = function(itemId) {
  const item = this.items.find(i => i.itemId.toString() === itemId.toString());
  return !!item && this.status === 'completed';
};

// Indexes
orderSchema.index({ user: 1, createdAt: -1 });
orderSchema.index({ status: 1 });

module.exports = mongoose.model('Order', orderSchema);